fail_fast: true

repos:
  - repo: https://github.com/ambv/black
    rev: 22.8.0
    hooks:
      - id: black
        args: [--line-length, "100"]

  - repo: https://github.com/PyCQA/autoflake
    rev: v1.5.0
    hooks:
      - id: autoflake
        args: [--in-place, --remove-all-unused-imports]

  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v0.971
  #   hooks:
  #     - id: mypy
  #       exclude: ^tests/
  #       args: [--strict]